# Generated by Django 2.1.4 on 2019-04-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_performer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='works_done',
        ),
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
