# Generated by Django 2.1.4 on 2018-12-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_performer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='performer'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_time',
            field=models.TextField(blank=True, default='', null=True, verbose_name='working time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='works_done',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='work done'),
        ),
    ]
