# Generated by Django 2.1.4 on 2019-04-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='family',
        ),
        migrations.RemoveField(
            model_name='client',
            name='otchesnvo',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Ф.И.О.'),
        ),
    ]
