# Generated by Django 2.1.4 on 2018-12-27 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20181227_1241'),
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Item')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость заказа')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка')),
                ('tirag', models.IntegerField(blank=True, default=0, null=True, verbose_name='Тираж')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Коментарий')),
                ('maket', models.ImageField(blank=True, null=True, upload_to='orders/', verbose_name='Макет')),
                ('dead_time', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Вип заказ')),
                ('delivery', models.BooleanField(default=False, verbose_name='Доставка')),
                ('delivery_address', models.TextField(blank=True, default='', null=True, verbose_name='Адрес доставки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Client')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='itemsinorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
    ]
