# Generated by Django 2.1.4 on 2018-12-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pp', models.IntegerField(default=1)),
                ('name', models.CharField(default='', max_length=255)),
                ('info', models.TextField(default='')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Свойство\\Товар',
                'verbose_name_plural': 'Свойства\\Товары',
            },
        ),
        migrations.CreateModel(
            name='MainCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pp', models.IntegerField(default=1)),
                ('name', models.CharField(default='', max_length=255)),
                ('discount', models.CharField(default='', max_length=255)),
                ('info', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Главная категория',
                'verbose_name_plural': 'Главные категории',
            },
        ),
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pp', models.IntegerField(default=1)),
                ('block', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('postobrab', models.BooleanField(default=False)),
                ('action_summ', models.BooleanField(default=False)),
                ('info', models.TextField(default='')),
                ('postobrab_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('main_cat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.MainCat')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sub_cat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SubCat'),
        ),
    ]
